[package]
name = "exect-core"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
inventory = "0.3.20"
postcard = { version = "1.1.1", features = ["alloc"] }
serde = { version = "1.0.219", features = ["alloc", "derive"] }
thiserror = "2.0.12"
